'use strict';

angular.module('app').config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	$stateProvider
		.state('main',{
		url:'/main',
		templateUrl:'view/main.html',
		controller:'mainCtrl'
		})
		.state('show',{
		url:'/show/:id',
		templateUrl:'view/show.html',
		controller:'showCtrl'
		})
		.state('positionList',{
		url:'/list',
		templateUrl:'view/positionList.html',
		controller:'poslistCtrl'
		})
		.state('position',{
		url:'/position/:id',
		templateUrl:'view/position.html',
		controller:'posCtrl'
		})
		.state('login',{
		url:'/login',
		templateUrl:'view/login.html',
		controller:'logCtrl'
		})
		.state('search',{
		url:'/search',
		templateUrl:'view/search.html',
		controller:'seaCtrl'
		})
		.state('home',{
		url:'/home',
		templateUrl:'view/home.html',
		controller:'homeCtrl'
		})
		.state('regist',{
		url:'/regist',
		templateUrl:'view/regist.html',
		controller:'regCtrl'
		})
		.state('collect',{
		url:'/collect',
		templateUrl:'view/collect.html',
		controller:'colCtrl'
		})
		.state('send',{
		url:'/send',
		templateUrl:'view/send.html',
		controller:'sendCtrl'
		});
	$urlRouterProvider.otherwise('main');	
}])